project_id = "xoampivltwofgecadktc"

[functions.process-referral-commission]
verify_jwt = false

[functions.firebase-phone-auth]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false

[functions.validate-coupon]
verify_jwt = false

[functions.award-yogic-points]
verify_jwt = false

[functions.activate-corporate-subscription]
verify_jwt = false

[functions.validate-corporate-coupon]
verify_jwt = false

[functions.admin-list-users]
verify_jwt = false
